# Dependências

In [1]:
import os
import sys
import pandas as pd
import numpy as np

from langchain_openai import OpenAIEmbeddings

from utils import load_data

from dotenv import load_dotenv
load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Tomando os usuários

In [2]:
DATA_DIR = "data"
users = load_data(DATA_DIR, "users.dat")

In [3]:
users

      UserID Gender  Age  Occupation Zip-code
0          1      F    1          10    48067
1          2      M   56          16    70072
2          3      M   25          15    55117
3          4      M   45           7    02460
4          5      M   25          20    55455
...      ...    ...  ...         ...      ...
6035    6036      F   25          15    32603
6036    6037      F   45           1    76006
6037    6038      F   56           1    14706
6038    6039      F   45           0    01060
6039    6040      M   25           6    11106

[6040 rows x 5 columns]

In [4]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   int64
 1   Gender      6040 non-null   object
 2   Age         6040 non-null   int64
 3   Occupation  6040 non-null   int64
 4   Zip-code    6040 non-null   object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB

In [5]:
user_num = 6040

### Dicionários de características
As informações foram extraídas da descrição fornecida pelo próprio grupo MovieLens. Está disponível em <a href="https://files.grouplens.org/datasets/movielens/ml-1m-README.txt">README - MovieLens 1M Dataset</a>.

In [6]:
gender_user_dict = {
    "M": "male",
    "F": "female"
}

In [7]:
age_user_dict = {
    1: "under 18",
    18: "18-24",
    25: "25-34",
    35: "35-44",
    45: "45-49",
    50: "50-55",
    56: "56+"
}

In [8]:
occupation_user_dict = {
    0:  "other or not specified",
	1:  "academic/educator",
	2:  "artist",
	3:  "clerical/admin",
	4:  "college/grad student",
	5:  "customer service",
	6:  "doctor/health care",
	7:  "executive/managerial",
	8:  "farmer",
	9:  "homemaker",
	10:  "K-12 student",
	11:  "lawyer",
	12:  "programmer",
	13:  "retired",
	14:  "sales/marketing",
	15:  "scientist",
	16:  "self-employed",
	17:  "technician/engineer",
	18:  "tradesman/craftsman",
	19:  "unemployed",
	20:  "writer"
}

## Gerando descrições de cada usuário

In [11]:
user_descriptions = [] # list of user descriptions
for i in range(1, user_num+1): # for each user
    user = users[users["UserID"] == i]
    description = f"Este é o usuário de ID {i}. Seu gênero é {gender_user_dict[user['Gender'].values[0]]} e sua idade está numa faixa etária de {age_user_dict[user['Age'].values[0]]} anos. Sua ocupação é como {occupation_user_dict[user['Occupation'].values[0]]} e reside em {user['Zip-code'].values[0]}."
    user_descriptions.append(description)

In [12]:
user_descriptions[:5]

['Este é o usuário de ID 1. Seu gênero é female e sua idade está numa faixa etária de under 18 anos. Sua ocupação é como K-12 student e reside em 48067.',
 'Este é o usuário de ID 2. Seu gênero é male e sua idade está numa faixa etária de 56+ anos. Sua ocupação é como self-employed e reside em 70072.',
 'Este é o usuário de ID 3. Seu gênero é male e sua idade está numa faixa etária de 25-34 anos. Sua ocupação é como scientist e reside em 55117.',
 'Este é o usuário de ID 4. Seu gênero é male e sua idade está numa faixa etária de 45-49 anos. Sua ocupação é como executive/managerial e reside em 02460.',
 'Este é o usuário de ID 5. Seu gênero é male e sua idade está numa faixa etária de 25-34 anos. Sua ocupação é como writer e reside em 55455.']

In [13]:
df_users_with_descriptions = pd.DataFrame(users["UserID"])
df_users_with_descriptions["Description_User"] = pd.Series(user_descriptions)

In [14]:
df_users_with_descriptions

      UserID                                   Description_User
0          1  Este é o usuário de ID 1. Seu gênero é female ...
1          2  Este é o usuário de ID 2. Seu gênero é male e ...
2          3  Este é o usuário de ID 3. Seu gênero é male e ...
3          4  Este é o usuário de ID 4. Seu gênero é male e ...
4          5  Este é o usuário de ID 5. Seu gênero é male e ...
...      ...                                                ...
6035    6036  Este é o usuário de ID 6036. Seu gênero é fema...
6036    6037  Este é o usuário de ID 6037. Seu gênero é fema...
6037    6038  Este é o usuário de ID 6038. Seu gênero é fema...
6038    6039  Este é o usuário de ID 6039. Seu gênero é fema...
6039    6040  Este é o usuário de ID 6040. Seu gênero é male...

[6040 rows x 2 columns]

### Embeddings

Aqui, nós usaremos um modelo de embedding da `OpenAI`.

In [15]:
model_embedding = OpenAIEmbeddings(api_key=OPENAI_API_KEY, model="text-embedding-3-large", dimensions=256)

In [16]:
embeddings_descriptions = model_embedding.embed_documents(user_descriptions)

In [17]:
embeddings_descriptions = np.array(embeddings_descriptions)
embeddings_descriptions

array([[-0.06174595,  0.08734955,  0.00565344, ...,  0.03881835,
         0.04929104,  0.0247116 ],
       [-0.02183977,  0.06732019, -0.00240459, ..., -0.00345032,
         0.07295204,  0.04718307],
       [-0.02291999,  0.05570921, -0.00344327, ..., -0.00266412,
         0.03522406,  0.00224208],
       ...,
       [-0.10194952,  0.06471147,  0.00417687, ...,  0.04425536,
         0.03511962,  0.01966169],
       [-0.07320732,  0.0748636 ,  0.01186721, ...,  0.01298519,
         0.02706352,  0.00669135],
       [-0.0431562 ,  0.08899917,  0.00172751, ...,  0.01194772,
         0.0111165 , -0.03353422]])

In [18]:
embeddings_descriptions.shape

(6040, 256)

In [19]:
embeddings_descriptions_df = pd.DataFrame(embeddings_descriptions)
embeddings_descriptions_df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,-0.061746,0.087350,0.005653,-0.007660,-0.032079,-0.017774,0.039842,0.041263,0.108229,0.072351,...,-0.045624,-0.046053,0.005637,-0.009060,0.044236,0.016461,0.094882,0.038818,0.049291,0.024712
1,-0.021840,0.067320,-0.002405,-0.006905,0.021529,0.055893,0.059298,0.039881,0.080418,0.085002,...,-0.073672,-0.068957,-0.053241,0.027848,0.032498,0.041453,0.082317,-0.003450,0.072952,0.047183
2,-0.022920,0.055709,-0.003443,0.000415,-0.014195,0.054670,0.007609,0.067656,0.099926,0.100316,...,-0.052073,-0.066877,-0.041847,0.029770,0.006582,0.022595,0.090381,-0.002664,0.035224,0.002242
3,-0.091243,0.099686,0.005494,0.035952,0.005554,0.052192,0.033433,0.071564,0.039153,0.096350,...,-0.078714,-0.034386,-0.085727,0.046404,-0.014316,0.013584,0.062815,-0.000455,0.013354,-0.017210
4,-0.061887,0.093187,-0.010950,-0.016162,-0.039743,0.068056,0.027356,0.062374,0.031495,0.069809,...,-0.073836,-0.084291,-0.083446,0.010983,-0.001396,0.052243,0.185855,0.015683,-0.004197,0.012006

In [20]:
df_users_with_descriptions_and_embeddings = pd.concat([df_users_with_descriptions, embeddings_descriptions_df], axis=1)
df_users_with_descriptions_and_embeddings.head(5)

,UserID,Description_User,0,1,2,3,4,5,6,7,...,246,247,248,249,250,251,252,253,254,255
0,1,Este é o usuário de ID 1. Seu gênero é female ...,-0.061746,0.087350,0.005653,-0.007660,-0.032079,-0.017774,0.039842,0.041263,...,-0.045624,-0.046053,0.005637,-0.009060,0.044236,0.016461,0.094882,0.038818,0.049291,0.024712
1,2,Este é o usuário de ID 2. Seu gênero é male e ...,-0.021840,0.067320,-0.002405,-0.006905,0.021529,0.055893,0.059298,0.039881,...,-0.073672,-0.068957,-0.053241,0.027848,0.032498,0.041453,0.082317,-0.003450,0.072952,0.047183
2,3,Este é o usuário de ID 3. Seu gênero é male e ...,-0.022920,0.055709,-0.003443,0.000415,-0.014195,0.054670,0.007609,0.067656,...,-0.052073,-0.066877,-0.041847,0.029770,0.006582,0.022595,0.090381,-0.002664,0.035224,0.002242
3,4,Este é o usuário de ID 4. Seu gênero é male e ...,-0.091243,0.099686,0.005494,0.035952,0.005554,0.052192,0.033433,0.071564,...,-0.078714,-0.034386,-0.085727,0.046404,-0.014316,0.013584,0.062815,-0.000455,0.013354,-0.017210
4,5,Este é o usuário de ID 5. Seu gênero é male e ...,-0.061887,0.093187,-0.010950,-0.016162,-0.039743,0.068056,0.027356,0.062374,...,-0.073836,-0.084291,-0.083446,0.010983,-0.001396,0.052243,0.185855,0.015683,-0.004197,0.012006

In [21]:
df_users_with_descriptions_and_embeddings.to_csv(os.path.join(DATA_DIR, "users_with_descriptions_and_embeddings_256_new.csv"))